doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            Auth:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Context/Auth/User/Infrastructure/Persistence/Doctrine/mapping'
                prefix: 'App\Context\Auth'
