framework:
    messenger:
        serializer:
            default_serializer: App\SharedKernel\Infrastructure\Bus\Serializer\MessageJsonSerializer
        default_bus: messenger.bus.auth.commands
        buses:
            messenger.bus.auth.commands:
                default_middleware: false
                middleware:
                    - doctrine_ping_connection
                    - dispatch_after_current_bus
                    - doctrine_transaction
                    - handle_message
            messenger.bus.auth.queries:
                default_middleware: false
                middleware:
                    - handle_message
            messenger.bus.auth.events:
                default_middleware: allow_no_handlers
        transports:
            async_auth_domain_event_bus:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 2
                options:
                    exchange:
                        name: domain_events
                        type: topic
                    queues:
                        auth_domain_events_queue:
                            binding_keys:
                                - 'company_name.auth.domain_event.#'
        routing:
            'App\Context\Auth\Event\AuthDomainEvent': async_auth_domain_event_bus
