framework:
    messenger:
        serializer:
            default_serializer: App\SharedKernel\Infrastructure\Bus\Serializer\MessageJsonSerializer
        default_bus: auth_domain_event_bus
        buses:
            auth_domain_event_bus:
                default_middleware: allow_no_handlers
        transports:
            async_auth_domain_event_bus:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 2
                options:
                    exchange:
                        name: domain_events
                        type: topic
                    queues:
                        auth_domain_events_queue:
                            binding_keys:
                                - 'company_name.auth.domain_event.#'
        routing:
            'App\Context\Auth\Event\AuthDomainEvent': async_auth_domain_event_bus
