security:
    enable_authenticator_manager: true
    providers:
        jwt_user:
            id: App\SharedKernel\Infrastructure\Symfony\Security\JwtUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - App\SharedKernel\Infrastructure\Symfony\Security\JwtAuthenticator

    access_control:
        - { path: ^/api/user/*, roles: PUBLIC_ACCESS }
        - { path: ^/api/user, roles: [ ROLE_ADMIN ] }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
