version: '3.5'

services:
  ddd-skeleton-web:
    container_name: ddd-skeleton-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - "1000:80"
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - ddd-skeleton-be
    networks:
      - ddd-skeleton-network

  ddd-skeleton-be:
    container_name: ddd-skeleton-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005 # Linux users
    volumes:
      - ./:/appdata/www
      - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini # Linux users
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - ddd-skeleton-db
    networks:
      - ddd-skeleton-network

  ddd-skeleton-db:
    container_name: ddd-skeleton-db
    image: mysql:8.0
    ports:
      - "3350:3306"
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - ddd-skeleton-db-data:/var/lib/mysql
    networks:
      - ddd-skeleton-network

volumes:
  ddd-skeleton-db-data:

networks:
  ddd-skeleton-network:
