imports:
    - { resource: '../src/SharedKernel/Infrastructure/Symfony/DependencyInjection/services.yaml' }
    - { resource: '../src/Context/Auth/User/Infrastructure/Symfony/DependencyInjection/services.yaml' }
