services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Context\User\User\:
    resource: '../../../'

  _instanceof:
    App\SharedKernel\Domain\Event\Message:
      tags: ['bus.messages']
    App\SharedKernel\Domain\Event\DomainEventListener:
      tags: ['messenger.message_handler']

  App\SharedKernel\Infrastructure\Bus\Serializer\MessageJsonSerializer:
    arguments:
      - !tagged_iterator bus.messages
